#!/bin/sh

# SYNTAX : auto-mount <drive> <user>

if [ -z "$1" ] || [ -z "$2" ]
then
  echo "error: no arguements"
  exit
fi

TARGET_DIRECTORY=/mnt
UUID=$(blkid $1 -o value | grep -)

# make directory off of the uuid
mkdir -p $TARGET_DIRECTORY/$UUID

# change ownership of the new directory to the current user
chown -R $2 $TARGET_DIRECTORY/$UUID
