#!/bin/sh

cd /usr/src/linux

make -j$(nproc --ignore 4)
make -j$(nproc --ignore 4) modules_install
make install

# clean up
cd /boot
rm *.old

echo "Reboot? (y/n)"
read choice

case $choice in
	y)
	  echo "Rebooting..."
	  reboot
	  ;;
	
	*)
	  echo "Quitting"
esac
