#!/bin/sh

# USAGE : start-vm <os>

case $1 in
	"gentoo")
		exec qemu-system-x86_64 -enable-kvm \
        	-cpu host \
        	-drive file=images/vm-gentoo.img,if=virtio \
        	-netdev user,id=vmnic,hostname=gentoo-vm \
        	-device virtio-net,netdev=vmnic \
        	-device virtio-rng-pci \
        	-m 512M \
        	-smp 2 \
        	-monitor stdio \
        	-name "Gentoo" \
		-boot d \
		-cdrom isos/gentoo.iso
	;;
	
	*)
		echo "os not found"
esac
